[package]
name = "test_extension"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "test_extension"
crate-type = ["cdylib", "staticlib"]

[dependencies]
